[workspace]
resolver = "2"
members = ["crates/core", "crates/cli"]

[workspace.package]
version = "0.2.1"
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/MrGilfy/appimg"
homepage = "https://github.com/MrGilfy/appimg"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
