[package]
name = "appimg"
description = "Install, update and remove AppImages as proper desktop applications"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "appimg"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
appimg-core = { path = "../core", version = "0.1.3" }
clap = { version = "4.5.61", default-features = false, features = ["derive", "std", "help", "usage", "error-context", "suggestions", "color", "wrap_help"] }
clap_complete = "4.5.67"
ratatui = "0.29.0"
tempfile = "3.27.0"

[dev-dependencies]

[build-dependencies]
clap = { version = "4.5.61", features = ["derive"] }
clap_complete = "4.5.67"
clap_mangen = "0.2.32"
